//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class waste
    {
        public int Waste_ID { get; set; }
        public string Waste_Name { get; set; }
        public byte[] Waste_Photo { get; set; }
        public string Waste_Info { get; set; }
        public Nullable<int> Label_ID { get; set; }
    
        public virtual label label { get; set; }
    }
}
