//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int location_id { get; set; }
        public Nullable<int> label_id { get; set; }
        public string town { get; set; }
        public string district { get; set; }
        public string address { get; set; }
    
        public virtual label label { get; set; }
    }
}
