//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSDraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class label
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public label()
        {
            this.locations = new HashSet<location>();
        }
    
        public int label_id { get; set; }
        public int waste_id { get; set; }
        public string label_name { get; set; }
        public byte[] label_photo { get; set; }
        public string label_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> locations { get; set; }
        public virtual waste waste { get; set; }
    }
}
